# Copied from Zeste de Savoir,
# https://github.com/zestedesavoir/zds-site/blob/a16c5fc932b361cbee5c6e61b24167605e24cd8b/.travis.yml

dist: trusty

language: python

python:
  - 2.7

git:
  depth: 1

cache:
  apt: true
  directories:
    - $HOME/.texlive
    - $HOME/bin

addons:
  apt:
    packages:
    - imagemagick
    - librsvg2-bin

install:
  - mkdir -p $HOME/bin
  - ./scripts/install_font.sh
  - ./scripts/install_texlive.sh
  - export PATH=$HOME/.texlive/bin/x86_64-linux:$PATH
  - pip install Pygments

script:
    - CURR=$(pwd)
    - TEMPLATEDIR=$HOME/.texlive/texmf-local/tex/latex/latex-template
    - TESTDIR=/tmp/latex-template-test
    - mkdir -p $TEMPLATEDIR && cp -r . $TEMPLATEDIR && texhash
    - mkdir -p $TESTDIR && cp -r ./tests/* $TESTDIR
    - cd $TESTDIR
    - patch Makefile < travis.patch # no cheating
    - make tests
    - cd $CURR
    - rm -Rf $TESTDIR && rm -Rf $TEMPLATEDIR # avoid the package to be cached!
    - texhash # avoid weird stuffs
