# Copied from Zeste de Savoir,
# https://github.com/zestedesavoir/zds-site/blob/a16c5fc932b361cbee5c6e61b24167605e24cd8b/.travis.yml

dist: trusty

language: python

python:
  - 2.7

git:
  depth: 1

cache:
  apt: true
  directories:
    - $HOME/.texlive
    - $HOME/bin

addons:
  apt:
    packages:
    - imagemagick
    - librsvg2-bin

install:
  - mkdir -p $HOME/bin
  - ./scripts/install_font.sh
  - ./scripts/install_texlive.sh
  - export PATH=$HOME/.texlive/bin/x86_64-linux:$PATH
  - pip install Pygments

script:
    - TMPL=$HOME/texmf/tex/generic/latex-template
    - mkdir -p $TMPL
    - cp -r . $TMPL
    - texhash
    - CURR=$(pwd)
    - TESTDIR=/tmp/latex-template-test
    - mkdir -p $TESTDIR
    - cp -r ./tests/* $TESTDIR
    - cd $TESTDIR
    - make tests
    - cd $CURR
    - rm -R $TESTDIR
